logging:
  level:
    root: INFO
    com.github.kerner1000.examples: DEBUG

#  Add this property to change output from:
#
# {"status":"UP"}
#
# to
#
#  {
#    "status":"UP",
#    "components":{
#      "diskSpace":{
#        "status":"UP",
#        "details":{
#          "total":994662584320,
#          "free":809682116608,
#          "threshold":10485760,
#          "exists":true
#        }
#      },
#      "ping":{
#        "status":"UP"
#      }
#    }
#  }
management.endpoint.health.show-details: "ALWAYS"

#  Add this property to change output from:
#
#  {
#    "_links":{
#      "self":{
#        "href":"http://localhost:8080/actuator",
#        "templated":false
#      },
#      "health":{
#        "href":"http://localhost:8080/actuator/health",
#        "templated":false
#      },
#      "health-path":{
#        "href":"http://localhost:8080/actuator/health/{*path}",
#        "templated":true
#      }
#    }
#  }
#
# to
#
#  {
#    "_links":{
#      "self":{
#        "href":"http://localhost:8080/actuator",
#        "templated":false
#      },
#      "beans":{
#        "href":"http://localhost:8080/actuator/beans",
#        "templated":false
#      },
#      "caches-cache":{
#        "href":"http://localhost:8080/actuator/caches/{cache}",
#        "templated":true
#      },
#      "caches":{
#        "href":"http://localhost:8080/actuator/caches",
#        "templated":false
#      },
#      "health-path":{
#        "href":"http://localhost:8080/actuator/health/{*path}",
#        "templated":true
#      },
#      "health":{
#        "href":"http://localhost:8080/actuator/health",
#        "templated":false
#      },
#      "info":{
#        "href":"http://localhost:8080/actuator/info",
#        "templated":false
#      },
#      "conditions":{
#        "href":"http://localhost:8080/actuator/conditions",
#        "templated":false
#      },
#      "configprops":{
#        "href":"http://localhost:8080/actuator/configprops",
#        "templated":false
#      },
#      "configprops-prefix":{
#        "href":"http://localhost:8080/actuator/configprops/{prefix}",
#        "templated":true
#      },
#      "env":{
#        "href":"http://localhost:8080/actuator/env",
#        "templated":false
#      },
#      "env-toMatch":{
#        "href":"http://localhost:8080/actuator/env/{toMatch}",
#        "templated":true
#      },
#      "loggers":{
#        "href":"http://localhost:8080/actuator/loggers",
#        "templated":false
#      },
#      "loggers-name":{
#        "href":"http://localhost:8080/actuator/loggers/{name}",
#        "templated":true
#      },
#      "heapdump":{
#        "href":"http://localhost:8080/actuator/heapdump",
#        "templated":false
#      },
#      "threaddump":{
#        "href":"http://localhost:8080/actuator/threaddump",
#        "templated":false
#      },
#      "metrics-requiredMetricName":{
#        "href":"http://localhost:8080/actuator/metrics/{requiredMetricName}",
#        "templated":true
#      },
#      "metrics":{
#        "href":"http://localhost:8080/actuator/metrics",
#        "templated":false
#      },
#      "scheduledtasks":{
#        "href":"http://localhost:8080/actuator/scheduledtasks",
#        "templated":false
#      },
#      "mappings":{
#        "href":"http://localhost:8080/actuator/mappings",
#        "templated":false
#      }
#    }
#  }
management.endpoints.web.exposure.include: "*"
